---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  Catalyst tool deployment on AWS. Includes Lambda functions and an endpoints deployed through API Gateway.
Parameters:
  NGDWrapperLambdaFunctionName: # Name of the NGD Wrapper Lambda function
    Type: String
    MinLength: "1"
    MaxLength: "64"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9_-]*"
    Description: The name of the NGD Wrapper Lambda function
    Default: Lambda-NGDWrapper
  NGDWrapperLambdaRoleName: 
    Type: String
    MinLength: "1"
    MaxLength: "64"
    AllowedPattern: '[\w+=,.@-]+'
    Description: The name of the IAM role used as the NGD Wrapper execution role
    Default: Lambda-NGDWrapper-Role
  NGDWrapperLambdaPolicyName:
    Type: String
    MinLength: "1"
    MaxLength: "128"
    AllowedPattern: '[\w+=,.@-]+'
    Default: Lambda-NGDWrapper-Policy
  ONSGeographiesLambdaFunctionName:
    Type: String
    MinLength: "1"
    MaxLength: "64"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9_-]*"
    Description: The name of the ONS Geographies Lambda function
    Default: Lambda-ONSGeographies
  ONSGeographiesLambdaRoleName:
    Type: String
    MinLength: "1"
    MaxLength: "64"
    AllowedPattern: '[\w+=,.@-]+'
    Description: The name of the IAM role used as the Lambda execution role
    Default: Lambda-ONSGeographies-Role
  ONSGeographiesLambdaPolicyName:
    Type: String
    MinLength: "1"
    MaxLength: "128"
    AllowedPattern: '[\w+=,.@-]+'
    Default: Lambda-ONSGeographies-Policy

Resources:

  NGDWrapperLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref NGDWrapperLambdaRoleName
      Description: An execution role for the NGD Wrapper Lambda function
      ManagedPolicyArns:
        - !Ref NGDWrapperLambdaPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"

  NGDWrapperLambdaPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref NGDWrapperLambdaPolicyName
      Description: Managed policy for a Lambda function launched by CloudFormation
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource:
              !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*"
          - Effect: Allow
            Action:
              - "logs:CreateLogGroup"
            Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:*"

  NGDWrapperLambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn:
      - NGDWrapperLambdaRole
      - NGDWrapperLambdaPolicy
    Properties:
      Description: Provides a wrapper for the NGD API
      FunctionName: !Ref NGDWrapperLambdaFunctionName
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Runtime: python3.13
      Role: !GetAtt NGDWrapperLambdaRole.Arn
      Timeout: 240
      Code:
        ZipFile: "https://github.com/Geovation/catalyst-ngd-wrappers-azure/releases/latest/download/release.zip"

  ONSGeographiesLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ONSGeographiesLambdaRoleName
      Description: An execution role for the ONS Geographies Proxy
      ManagedPolicyArns:
        - !Ref ONSGeographiesLambdaPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"

  ONSGeographiesLambdaPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref ONSGeographiesLambdaPolicyName
      Description: Managed policy for a Lambda function
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource:
              !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*"
          - Effect: Allow
            Action:
              - "logs:CreateLogGroup"
            Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:*"

  ONSGeographiesLambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn:
      - ONSGeographiesLambdaRole
      - ONSGeographiesLambdaPolicy
    Properties:
      Description: Proxy for the ONS Geographies Proxy
      FunctionName: !Ref ONSGeographiesLambdaFunctionName
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Runtime: python3.13
      Role: !GetAtt ONSGeographiesLambdaRole.Arn
      Timeout: 240
      Code:
        ZipFile: "https://raw.githubusercontent.com/geovation/catalyst-deployment/refs/heads/main/aws/sample.zip"

  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Catalyst
      Description: API Gateway deployment for Geovation Catalyst tools. Deployed through CloudFormation.
      EndpointConfiguration:
        Types:
          - REGIONAL

  EndpointBase:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      RestApiId: !Ref ApiGatewayRestApi
      PathPart: 'catalyst'

  EndpointONSGeographies:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref EndpointBase
      RestApiId: !Ref ApiGatewayRestApi
      PathPart: 'ons-geographies'

  EndpointONSGeographiesPlaces:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref EndpointONSGeographies
      RestApiId: !Ref ApiGatewayRestApi
      PathPart: 'places'

  EndpointONSGeographiesPlacesOperation:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref EndpointONSGeographiesPlaces
      RestApiId: !Ref ApiGatewayRestApi
      PathPart: '{operation}'

  EndpointLatestCollections:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref EndpointBase
      RestApiId: !Ref ApiGatewayRestApi
      PathPart: 'latest-collections'
  
  EndpointLatestCollectionsCollection:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref EndpointLatestCollections
      RestApiId: !Ref ApiGatewayRestApi
      PathPart: '{collection}'

  EndpointFeatures:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref EndpointBase
      RestApiId: !Ref ApiGatewayRestApi
      PathPart: 'features'

  EndpointFeaturesCollection:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref EndpointFeatures
      RestApiId: !Ref ApiGatewayRestApi
      PathPart: '{collection}'

  EndpointFeaturesCollectionItems:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref EndpointFeaturesCollection
      RestApiId: !Ref ApiGatewayRestApi
      PathPart: 'items'

  EndpointFeaturesCollectionItemsFunction:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref EndpointFeaturesCollectionItems
      RestApiId: !Ref ApiGatewayRestApi
      PathPart: '{function}'

  MethodONSGeographies:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      HttpMethod: GET
      AuthorizationType: NONE
      ResourceId: !Ref EndpointONSGeographiesPlacesOperation
      RestApiId: !Ref ApiGatewayRestApi
      Integration:
        Type: AWS
        IntegrationHttpMethod: GET
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations
          - lambdaArn: !GetAtt ONSGeographiesLambdaFunction.Arn
  
  MethodLatestCollections:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      HttpMethod: GET
      AuthorizationType: NONE
      ResourceId: !Ref EndpointLatestCollections
      RestApiId: !Ref ApiGatewayRestApi
      Integration:
        Type: AWS
        IntegrationHttpMethod: GET
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations
          - lambdaArn: !GetAtt NGDWrapperLambdaFunction.Arn

  MethodLatestCollectionsCollection:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      HttpMethod: GET
      AuthorizationType: NONE
      ResourceId: !Ref EndpointLatestCollectionsCollection
      RestApiId: !Ref ApiGatewayRestApi
      Integration:
        Type: AWS
        IntegrationHttpMethod: GET
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations
          - lambdaArn: !GetAtt NGDWrapperLambdaFunction.Arn
  
  MethodItems:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      HttpMethod: GET
      AuthorizationType: NONE
      ResourceId: !Ref EndpointFeaturesCollectionItems
      RestApiId: !Ref ApiGatewayRestApi
      Integration:
        Type: AWS
        IntegrationHttpMethod: GET
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations
          - lambdaArn: !GetAtt NGDWrapperLambdaFunction.Arn

  MethodItemsFunction:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      HttpMethod: GET
      AuthorizationType: NONE
      ResourceId: !Ref EndpointFeaturesCollectionItemsFunction
      RestApiId: !Ref ApiGatewayRestApi
      Integration:
        Type: AWS
        IntegrationHttpMethod: GET
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations
          - lambdaArn: !GetAtt NGDWrapperLambdaFunction.Arn

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - MethodLatestCollections
      - MethodLatestCollectionsCollection
      - MethodItems
      - MethodItemsFunction
      - MethodONSGeographies
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      StageName: 'prod'
      Description: 'CatalyST API Gateway Deployment'